<div>
<img src="/upds/famous/logo/bnr_{f}.jpg" width="1217" height="198" onerror="this.src='html/def/img/banner.jpg';"/>
</div>
<div class="f_nav">
<div class="f_nav_content">
<ul>
<li><a href="./?f={f}">首页</a></li>
<li><a href="./?t=intro&f={f}">工作室简介</a></li>
<li class="menu-item"><a href="./?t=news&f={f}">工作室动态</a></li>
<li><a href="./?t=mien&f={f}">团队风采</a></li>
<li><a href="./?t=member&f={f}">团队成员</a></li>
<li class="none"><a href="./man/?f={f}" target=_blank>[管理]</a> </li>
</ul>
</div>

<div class="f_nav_right">
<ul> 
<li><a href="/school/?s={school}">学校</a></li> 
<li><a href="/subjecter">学科</a></li>
</ul>
</div>

</div>