<div class="col-sm-2  navbar-default">
<div class="row">
  <div class="col-sm-6 text-center">
  <a><img src="{face}"  style="width:72px;"  /></a> 
  </div>   
  <div class="col-sm-6">
    <h4>{nick} <br/>
    <small>{truename} </small></h4>
    <span class="text-muted">{ename}  </span>   
  </div>
</div> 
<div class="row"> 
<code  class="text-info"><a href="./?t=weibo">微博{weibo}</a> | <a href="./?t=blogs">博客{blog}</a> | 关注{} </code>
<br/><code  class="text-info"> 经验{} </code> 
</div> 
<hr/> 
<ul class="nav">    
<li> <a href="./">主页</a></li>

<li>  <a href="./?t=homework">我的作业</a>  </li> 
<li> <a href="./?t=datum" >学习资料</a> </li>  
<li><a href="./?t=note">笔记</a> </li>
<li><a href="./?t=score">成绩</a> </li>   

<li> <a href="./?t=courseware">订阅课件...</a></li>
<li> <a href="./?t=class" >我的班级</a> </li>  
<li> <a href="./?t=group" >我的群</a> </li>   
<li> <a href="./?t=school" >我的学校</a> </li>  
 <li> <a href="./?t=info" >我的信息</a> </li> 
 <li><a href="./?t=applist">应用中心</a>  </li> 
</ul> 
<h4>互动</h4>
<ul class="nav">
  <li><a href="./?t=blogs">我的博客</a></li> 
  <li><a href="./?t=weibo">我的微博</a></li> 
</ul> 
<h4>其它</h4>
<ul class="nav nav-sidebar">
<li> <a href="./?t=timetable">课表</a></li>   
<li><a href="./?t=schedule">日程</a>  </li> 
<li><a href="./?t=faq">FAQ</a>  </li>  
</ul>
</div>