<li class="link lf"><a href="/school?s={school}">学校</a> <span><a href="/subject?s={school}">学科</a></span></li>
    </ul>
  
    </div>
    <div class="list lf">
    <a href="./?g={g}" ><div>主页</div></a>
    <a href="/group?t=forum&g={g}">
    <div>群论坛	</div></a>
    <a href="/group?t=album&g={g}"">
    <div>群相册</div></a>
	 <a href="/group?t=file&g={g}">
    <div class="hide">群文件</div></a>	
    <a href="/group?t=member&g={g}">
    <div>群成员</div></a>
	<a  href="/group/man?g={g}" target=_blank>
    <div>[管理]</div></a> 
     </div>