<meta charset="gbk">   
<link rel="stylesheet" href="/widget/bootstrap/css/bootstrap.min.css">  
<!--[if lt IE 9]>
<script src="/ppf/js/jquery-1.min.js"></script>
<script src="/ppf/js/html5shiv.min.js"></script>
<script src="/ppf/js/respond.js"></script>  
<![endif]-->
<!--[if gt IE 8]>
<script src="/ppf/js/jquery-2.min.js"></script> 
<![endif]-->
<!--[if !IE]><!--> 
<script src="/ppf/js/jquery-2.min.js"></script> 
<!--<![endif]-->
<script src="/widget/bootstrap/js/bootstrap.min.js"></script>   
<script src="/ppf/js/jquery.base64.js" type="text/javascript"></script>
<script src="/ppf/js/cookies.min.js" type="text/javascript"></script> 
<script src="/ppf/js/fun.js" type="text/javascript"></script> 
<script src="/ppf/js/frtdo.js" type="text/javascript"></script>
<script src="/ppf/js/select.js" type="text/javascript"></script>
<script src="/js/comm_login_bt.js" type="text/javascript"></script>
<script src="js/local.js" type="text/javascript"></script>

<link rel="stylesheet" href="/zone/css/common.css">
