<div class="oa_index_topleft">
   <div class="index_userpic">
     <div class="index_userpic_left"><img src="image/oa_user.png" width="67" height="65"  alt=""/></div>
     <div class="index_userpic_right">
       <div class="index_userpic-font"><span>张三丰</span></div>
       <div class="index_userpic-font">2016年4月23日 星期五</div>
     </div>
   </div>
  </div>
  <div class="oa_index_topmid">
    <div class="oa_index_title">海安中学学生成长系统</div>
  </div>
  <div class="oa_index_topright">
   <div class="oa_index_topsetting">
      <span>反馈</span>&nbsp;&nbsp;<img src="image/oa_email.png" width="23" height="23"  alt=""/>&nbsp;&nbsp;
    <img src="image/oa_setting.png" width="26" height="23"  alt=""/> &nbsp;&nbsp;<img src="image/oa_pf.png" width="24" height="23"  alt=""/>
     </div>
  </div>