<div style="margin-left:6px;">
      <div class="stu-menu-hint">用户设置</div>
      <div class="stu-menu-hint-item">
        <div class="stu-menu-hint-image"><img src="image/oa_u.png" width="49" height="48"  alt=""/></div>
        <div><a href="./?t=up_pass"><span>个人信息</span></a></div>
      </div>
      <div class="oa_clear"></div>
      <div class="stu-menu-hint-item">
        <div class="stu-menu-hint-image"><img src="image/oa_pass.png" width="49" height="49"  alt=""/></div>
        <div><a href="./?t=index"><span>修改密码</span></a></div>
      </div>
      <div class="oa_clear"></div>
      <div class="stu-menu-hint">控制面板</div>
      <div class="stu-menu-index">
      <!--star-->
        <div class="stu-menu-item">
            <div class="stu-menu-item-image"><img src="image/oa_zhsz.png" width="21" height="23"  alt=""/></div>
            <div><span>综合素质评价</span></div>
            <div class="stu-menu-item-right"><img src="image/oa_zk.png" width="16" height="17"  alt="" onClick="hideClick('sz')"/></div>
        </div>
        <div id="sz">
           <div class="stu-menu-itemchild">
            -&nbsp; 内容管理
           </div>
           <div class="stu-menu-itemchild">
            -&nbsp; 内容管理
           </div>
           <div class="stu-menu-itemchild">
            -&nbsp; 内容管理
           </div>
           <div class="stu-menu-itemchild">
            -&nbsp; 内容管理
           </div>
           <div class="stu-menu-itemchild">
            -&nbsp; 内容管理
           </div>
        </div>
       <div class="oa_clear"></div>
        <div class="stu-menu-item">
            <div class="stu-menu-item-image"><img src="image/oa_school.png" width="21" height="20"  alt=""/></div>
            <div onClick="hideClick('scz')"><span>学校设置</span></div>
            <div class="stu-menu-item-right"><img src="image/oa_zk.png" width="16" height="17"  alt="" onClick="hideClick('scz')"/></div>
        </div>
        <div id="scz">
           <div class="stu-menu-itemchild">
            -&nbsp; 内容管理
           </div>
           <div class="stu-menu-itemchild">
            -&nbsp; 内容管理
           </div>
           <div class="stu-menu-itemchild">
            -&nbsp; 内容管理
           </div>
           <div class="stu-menu-itemchild">
            -&nbsp; 内容管理
           </div>
           <div class="stu-menu-itemchild">
            -&nbsp; 内容管理
           </div>
        </div>
        <div class="oa_clear"></div>
        <div class="stu-menu-item">
            <div class="stu-menu-item-image"><img src="image/oa_if.png" width="21" height="18"  alt=""/></div>
            <div onClick="hideClick('xfgl')"><span>成绩/学分管理</span></div>
            <div class="stu-menu-item-right"><img src="image/oa_zk.png" width="16" height="17"  alt="" onClick="hideClick('xfgl')"/></div>
        </div>
        <div id="xfgl">
           <div class="stu-menu-itemchild">
            -&nbsp; 内容管理
           </div>
           <div class="stu-menu-itemchild">
            -&nbsp; 内容管理
           </div>
           <div class="stu-menu-itemchild">
            -&nbsp; 内容管理
           </div>
           <div class="stu-menu-itemchild">
            -&nbsp; 内容管理
           </div>
           <div class="stu-menu-itemchild">
            -&nbsp; 内容管理
           </div>
        </div>
        <div class="oa_clear"></div>
        <div class="stu-menu-item">
            <div class="stu-menu-item-image"><img src="image/oa_sz.png" width="21" height="19"  alt=""/></div>
            <div onClick="hideClick('xfgl')"><span>技能素质导入</span></div>
            <div class="stu-menu-item-right"><img src="image/oa_zk.png" width="16" height="17"  alt="" onClick="hideClick('xfgl')"/></div>
        </div>
        <div id="xfgl">
           <div class="stu-menu-itemchild">
            -&nbsp; 内容管理
           </div>
        </div>
        <div class="oa_clear"></div>
        <div class="stu-menu-item">
            <div class="stu-menu-item-image"><img src="image/oa_jc.png" width="21" height="17"  alt=""/></div>
            <div onClick="hideClick('xfgl')"><span>学生奖惩管理</span></div>
            <div class="stu-menu-item-right"><img src="image/oa_zk.png" width="16" height="17"  alt="" onClick="hideClick('xfgl')"/></div>
        </div>
        <div id="xfgl">
           <div class="stu-menu-itemchild">
            -&nbsp; 内容管理
           </div>
        </div>
        <div class="oa_clear"></div>
        <div class="stu-menu-item">
            <div class="stu-menu-item-image"><img src="image/oa_tz.png" width="21" height="12"  alt=""/></div>
            <div onClick="hideClick('xfgl')"><span>体质体能管理</span></div>
            <div class="stu-menu-item-right"><img src="image/oa_zk.png" width="16" height="17"  alt="" onClick="hideClick('xfgl')"/></div>
        </div>
        <div id="xfgl">
           <div class="stu-menu-itemchild">
            -&nbsp; 内容管理
           </div>
        </div>
        <div class="oa_clear"></div>
        <div class="stu-menu-item">
            <div class="stu-menu-item-image"><img src="image/oa_pj.png" width="21" height="25"  alt=""/></div>
            <div onClick="hideClick('xfgl')"><span>评价管理</span></div>
            <div class="stu-menu-item-right"><img src="image/oa_zk.png" width="16" height="17"  alt="" onClick="hideClick('xfgl')"/></div>
        </div>
        <div id="xfgl">
           <div class="stu-menu-itemchild">
            -&nbsp; 内容管理
           </div>
        </div>
        <div class="oa_clear"></div>
        <div class="stu-menu-item">
            <div class="stu-menu-item-image"><img src="image/oa_system.png" width="21" height="19"  alt=""/></div>
            <div onClick="hideClick('xfgl')"><span>系统管理</span></div>
            <div class="stu-menu-item-right"><img src="image/oa_zk.png" width="16" height="17"  alt="" onClick="hideClick('xfgl')"/></div>
        </div>
        <div id="xfgl">
           <div class="stu-menu-itemchild">
            -&nbsp; 内容管理
           </div>
        </div>
        <!--end-->
        <div style="height:15px;"></div>
         <div class="stu-menu-hint-item">
            <div class="stu-menu-hint-image"><img src="image/oa_close.png" width="49" height="49"  alt=""/></div>
            <div><span>退出系统</span></div>
        </div>
         <div style="height:15px;"></div>
      </div>
     </div>