<div class="logo_out w1" style="background:url(/upds/class/logo/{c}_1000.jpg);">
	<div class="logo">
		<img src="/upds/class/logo/{c}.jpg" onerror="this.src='/error/logo.jpg';" width="100" height="100"/>
	</div>
	<div class="text_logo">
		<p>{name} </p>
		<span>{slogan} 寄语：{wishes}</span>
	</div>
</div>
<div class="w1 nav">
	<div class="main">
		<div class="menu">
			<ul>                                
				<li><a href="./?c={c}" target="">首页</a></li>
				<li><a href="./?t=mem_saying&c={c}" target="">老师语录</a></li>
				<li><a href="./?t=cls_notice&c={c}" target="">通知公告</a></li>
				<li><a href="./?t=cls_activity&c={c}" target="">动态</a></li>
				<li><a href="./?t=cls_diary&c={c}" target="">日记</a></li>
				<li><a href="./?t=cls_album&c={c}" target="">相册</a></li>
				<li><a href="./?t=cls_honor&c={c}" target="">荣誉</a></li>
				<li><a href="./?t=mem_tech&c={c}" target="">成员</a></li>
				<li><a href="./man/?c={c}" target=_blank>管理</a></li>
			</ul>
		</div>
		<div class="menu_r">
			<ul> 
				<li><a href="/subject?s={s}" target="">学科</a></li>
				<li><a href="/school?s={s}" target="">学校</a></li>
			</ul>
		</div>
	</div>
</div>