<?php
define('LR_DEBUG', 1);
define('LR_NAME', '教育信息化平台');    
define('LR_VER', 'ver2.5_1427版');
define('LR_MAIL', 'webabc@topnt.cn');
define('LR_TEL', '4000-025-085');      
define('BASE_DNS', '127.0.0.1');
define('GOTO_URL', '/oa/');

#local define   
define('INTEGRAL_NUM',5);//积分基数
define('GOLD_NAME','财富豆');//金币名称  

#sync
define('LR_SID', 'M01');
define('LR_SNAME', '中心服务器'); 
define('BASE_URL', 'http://yun.365sns.net:880/');
define('BASE_KEY', '35892595f7d2156edaef8badd7fb14f6'); 

#global
define('DIR_ROOT', $_SERVER['DOCUMENT_ROOT']); 
define('REG_OFF', '0');    
define('IP_ERR_CHK',1); 
define('IP_ERR_NUM','10');
define('RESET_PASS_URI','http://oa.hazx.org.cn:8011/?t=reset');
define('CACHE_PAGE',1);
define('CACHE_TIME',3600); 
                                                           
#database
define('DB_DATABASE', 'mysql'); 
define('DB_HOST', '');   
define('DB_PORT', 3306);  
define('DB_USER', 'root');	
define('DB_PWD', '');	
define('DB_NAME', 'xsczpt');	
define('DB_CHARSET', 'utf8');
define('DATA_PRE', 'a');	
  
#pan
define('PAN_URL', 'http://pan.365sns.net:880/');    
#update dir
define('UP_FACE', '/upd/face/');
define('UP_PIC_DIR', '/upds/pic/');  
define('UP_FILE_DIR', '/upds/');  

#tydl
define('APP_URL', 'http://uc.jssns.cn/');
define('APP_API_URL', 'http://uc.jssns.cn/api/jsonp/');
define('APPID', '1050');  
define('APPKEY', '5072416'); 
define('APPORGID', '103');  
define('APPIDTYPE', '11'); 