<ul class="list-group" style="margin-top:20px;">
<li class="list-group-item active"><h5>名师管理中心</h5></li>
<li class="list-group-item"><a href="/famous?f={f}"><i class="glyphicon glyphicon-arrow-left"></i>返回首页</a></li>
<li class="list-group-item"><a href="./?f={f}">基本信息</a></li>  
<li class="list-group-item"><a href="./?t=member&f={f}">工作室成员</a> </li>
<li class="list-group-item"><a href="./?t=slide&f={f}">幻灯片</a> </li>
<li class="list-group-item"><a href="./?t=team_mien&f={f}">团队风采</a> </li>    
<li class="list-group-item">文章管理
<ul  class="ul1">
<li><a href="./?t=art_list&f={f}">文章管理</a> </li> 
<li><a href="./?t=art_cate&f={f}">类别管理</a> </li>
</ul>
</li>

<li class="list-group-item">famousZone设置
<ul  class="ul1">
<li><a href="./?t=famousZone&f={f}">模板设置</a> </li> 
</ul>
</li>

<li class="list-group-item hide">资源管理
<ul>    
<li><a href="#">课件分享</a> </li> 
<li><a href="#">视频教学</a> </li>
<li><a href="#">出版作品</a> </li> 
</ul>
</li>  

</ul>   
