<div class="logo"><img src="/read/html/read/images/logo.jpg" width="500" height="95" /></div>
<ul class="rea_menu">                                                                                                
<li><a href="./" target="">首页</a>
<li><a href="./?t=art_list&pc=16" target="">新闻公告</a>
<li><a href="./?t=recommend" target="">图书推荐</a>
<li><a href="./?t=art_list&pc=18" target="">读后感</a>
<li><a href="./?t=recommend_lists&pid=32" target="">专题推荐</a>
<li><a href="./?t=art_list&pc=20" target="">书香视听</a>
<li><a href="./?t=activity" target="">读书活动</a>
<li><a href="./?t=works" target="">学生作品</a>
<!-- <li><a href="#" target="">工作室</a>
<li><a href="#" target="">群组</a>
<li><a href="#" target="">班级</a>
<li><a href="#" target="">课程</a> -->
</ul>