

<div class="panel panel-default">
<div class="panel-heading"><h3 class="panel-title">办公空间</h3></div>
<div class="panel-body" style="padding:0;">
<ul class="nav"> 
<li> <a href="?t=timetable">课表</a></li>   
<li><a href="?t=schedule">日程</a>  </li>  
<li><a href="?t=faq">FAQ</a>  </li> 
<li class="hide"> <a href="#">成绩</a></li>     
<li></li>  
</ul> 
</div>
</div>

<div class="panel panel-default">
<div class="panel-heading"><h3 class="panel-title">活动管理</h3></div>
<div class="panel-body" style="padding:0;">
<ul class="nav">
<li> <a href="?t=active_my">我发起的活动</a></li>    
<li> <a href="?t=active_partin">参与的活动</a></li>  
<li> <a href="?t=active_fav">收藏夹</a></li>    
<li></li>                                         
</ul> 
</div>
</div>

<div class="panel panel-default">
<div class="panel-heading"><h3 class="panel-title">教师发展</h3></div>
<div class="panel-body" style="padding:0;">
<ul class="nav">
<li> <a href="?t=deve_list">成长</a></li>  
<li> <a href="?t=deve_cate">类别</a></li> 
<li> <a href="?t=deve_info">基本信息</a></li>    
<li></li>                                         
</ul> 
</div>
</div>

<div class="panel panel-default">
<div class="panel-heading"><h3 class="panel-title">组织机构</h3></div>
<div class="panel-body" style="padding:0;">
<ul class="nav">
<li><a href="?t=school" class="fa fa-building-o"> 我的学校</a></li>
<li><a href="?t=class" class="fa fa-circle-o-notch"> 我的班级</a> </li>
<li><a href="?t=group" class="fa fa-group"> 我的群组</a></li>
<li><a href="?t=famous" class="fa fa-graduation-cap"> 我的工作室</a> </li>
<li></li>    
</ul> 
</div>
</div>


