<div class="panel panel-default">
<div class="panel-heading"><h3 class="panel-title">个人空间<small></small> </h3></div>
<div class="panel-body">
<ul class="nav">
<li><a href="?t=blogs">我的博客</a></li> 
<li><a href="?t=weibo">我的微博</a></li> 
<li><a href="{panurl}" target=_blank>我的网盘</a></li> 
<li><a href="?t=album">我的相册</a></li>    
<li><a href="?t=leave">留言板</a></li>  
<li><a href="?t=fav">收藏夹</a></li>  
<li class="divider"><hr/></li>
<li><a href="/user/?t=frd">好友管理</a></li>  
<li><a href="/user/?t=zone_set">zone设置</a></li>  
 <li><a href="/user"  class="fa fa-cog">设置中心</a></li>
 <li><a href="/zone?id={uid}" target=_blank><i class="fa fa-search"></i> Zone预览</a></li>   
</ul> 
</div>
</div>

