<div class="panel panel-default">
<div class="panel-heading"><h3 class="panel-title">教学空间<small></small></h3></div>
<div class="panel-body">
<ul class="nav">
<li><a href="?t=courseware">课件</a></li>
<li><a href="?t=homework">作业</a>  </li>   
<li><a href="?t=preparelesson" >备课</a> </li>     
<li><a href="?t=itembank">题库</a> </li>     
<li><a href="?t=textbook">课文库</a>  </li> 
<li></li>  
</ul> 
</div>
</div>