<div class="col-sm-2  navbar-default">
<div class="row">
  <div class="col-sm-6 text-center">
  <a><img src="{face}"  style="width:72px;"  onerror="this.src='/error/face.jpg';" /></a> 
  </div>   
  <div class="col-sm-6">
    <h4>{nick}<br/>
    <small>{truename} </small></h4>
    <span class="text-muted">{ename}  </span>   
  </div>
</div> 
<div class="row"> 
<code  class="text-info"><a href="./?t=weibo">微博({weibo})</a> | <a href="./?t=blogs">博客({blog})</a></code> 
</div> 
<hr/> 
<ul class="nav">    
  <li> <a href="./" >主页</a></li>
  <li> <a href="./?t=timetable">课表</a></li>
  <li> <a href="./?t=homework">作业</a>  </li>
  <li> <a href="./?t=schedule">学习计划</a>  </li>
  <li> <a href="./?t=faq">FAQ</a>  </li> 
  <li> <a href="./?t=class">班级</a> </li> 
  <li> <a href="./?t=group" >群组</a> </li>      
  <li> <a href="./?t=score">成绩</a> </li>
  <li> <a href="./?t=children">子女设置</a></li>
  <li> <a href="./?t=info">空间信息</a></li> 
</ul>
<h4>互动</h4>
<ul class="nav">
  <li><a href="./?t=blogs">我的博客</a></li> 
  <li><a href="./?t=weibo">我的微博</a></li> 
</ul> 
</div>