<meta charset="gbk">   
<link rel="stylesheet" href="/widget/bootstrap/css/bootstrap.min.css">  
<script src="/ppf/js/jquery-2.min.js"></script>                    
<script src="/widget/bootstrap/js/bootstrap.min.js"></script>   
<script src="/ppf/js/jquery.base64.js" type="text/javascript"></script>
<script src="/ppf/js/cookies.min.js" type="text/javascript"></script> 
<script src="/ppf/js/fun.js" type="text/javascript"></script> 
<script src="/js/comm_login_bt.js" type="text/javascript"></script>
<script src="/js/local.js" type="text/javascript"></script>

<script type="text/javascript" src="/widget/datepicker/WdatePicker.js"></script>
<script src="/ppf/js/frtdo.js" type="text/javascript"></script>
<script src="/ppf/js/select.js" type="text/javascript"></script>
<script src="js/active.js" type="text/javascript"></script> 

<script src="js/vote.js" type="text/javascript"></script>
<link href="/html/white/css/plat.css" rel="stylesheet" type="text/css"> 