<ul id="myTab" class="nav nav-tabs">
   <li><a href="/?t=actives">最新活动</a></li> 
   <li><a href="/?t=actived">活动回顾</a></li>
   <li class="dropdown hide">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">我的活动<b class="caret"></b></a>
      <ul class="dropdown-menu" role="menu">
         <li><a href="/activity?t=my_active">我发起的活动</a></li>
         <li><a href="/activity?t=my_partin">我参加的活动</a></li>
         <li><a href="/activity?t=my_fav">我收藏的活动 </a></li>
      </ul>
   </li>
  <li class="pull-right"><a href="/tech/work.php?t=active_my" target=_blank>我发起的活动</a></li>
   <li class="pull-right"> <a href="/tech/work.php?t=active_push" class="btn btn-primary" target=_blank> + 发起活动</a></li>
</ul>