<meta charset="utf-8"> 
<script src="/ppf/js/jquery-1.min.js" type="text/javascript"></script> 
<script src="/ppf/js/jquery.base64.js" type="text/javascript"></script>    
<script src="/ppf/js/fun.js" type="text/javascript"></script>  
<script src="/ppf/js/select.js" type="text/javascript"></script>   
<script src="js/runpage.js" type="text/javascript"></script>
<script src="js/bskdlg.js" type="text/javascript"></script>
<script src="js/bskdo.js" type="text/javascript"></script> 
<script src="/widget/datepicker/WdatePicker.js" type="text/javascript"></script>
<script src="/widget/layerv2/layer/layer.js" type="text/javascript"></script>

<link href="css/blue.css" rel="stylesheet">

<script type="text/javascript" src="/widget/easyui/jquery.easyui.min.js"></script> 
<link rel="stylesheet" type="text/css" href="/widget/easyui/themes/default/dialog.css"> 
<link rel="stylesheet" type="text/css" href="/widget/easyui/themes/default/panel.css"> 
 <link rel="stylesheet" type="text/css" href="/widget/easyui/themes/default/window.css">  
<link rel="stylesheet" type="text/css" href="/widget/easyui/themes/default/linkbutton.css">  