<link rel="stylesheet" type="text/css" href="./img_tpl/common.css">
<div class="select-header" style="background:url(/upds/class/logo/{c}_1000.jpg);">
<li>
<img src="/upds/class/logo/{c}.jpg"  onerror="this.src='/error/logo.jpg';" alt="{name}" width="100" height="100"/>
</li>
<li>
<div class="biaoji">
<h3>{name} <small>口号：{slogan}</small></h3>
<p><small>寄语：{wishes}</small></p>
</div>
<div class="menu" style="width:600px;float:left;">
<span class="menu_a"><i></i><a href="./?c={c}">首页</a></span>
<span class="menu_c"><a href="./?t=mem_saying&c={c}">老师语录</a></span>
<span class="menu_d"><a href="./?t=cls_notice&c={c}">通知公告</a></span>
<span class="menu_b"><a href="./?t=cls_activity&c={c}">动态</a></span>
<span class="menu_d"><a href="./?t=cls_diary&c={c}">日记</a></span>
<span class="menu_d"><a href="./?t=cls_album&c={c}">相册</a></span>
<span class="menu_d"><a href="./?t=cls_honor&c={c}">荣誉</a></span>
<span class="menu_c"><a href="./?t=mem_tech&c={c}">成员</a></span>
<span class="menu_d"><a href="./man/?c={c}" target=_blank>【管理】</a></span>
</div>
<div class="" style="float:right;margin-top:6px;">
<ul class="class_index_nav_right">         
<li><a href="/school?s={s}"  class="">学校</a></li>
<li><a href="/subject?s={s}"  class="">学科</a></li> 

</ul>
</div>
</li>
</div>