<div class="container top"> 
   <div class="row">
      <div class="col-xs-12"> 
        <div class="top-name" alt="{truename}">
          <h3>{name}<small>{explain}</small></h3>
        </div>
        <div class="top-nav">
          <ul class="nav navbar-nav">
            <li><a href="./?t=index&id={zid}"> ◊“≥</a></li>
            <li><a href="./?t=weibo&id={zid}">Œ¢≤©</a></li>
            <li><a href="./?t=bloga&id={zid}">≤©øÕ</a></li>
            <li><a href="./?t=album&id={zid}">œ‡≤·</a></li> 
            <li><a href="./?t=board&id={zid}">¡Ù—‘∞Â</a></li>
            <li class="hide"><a href="./?t=fav&frid={frid}"> ’≤ÿº–</a></li>
          </ul>
        </div>
      </div>
   </div>
</div>
