<div class="head">
			<div class="logo"><img src="/html/white/images/logo1.jpg" height="67" /></div>
			<div class="ban_head"><img src="/html/white/images/ban_head.jpg" width="250" height="110" /></div>
		</div>
		<div class="clear"></div>
		<div class="qjf_findnav">
			<ul>
				<li id="school" style="border-left-width: 0px;" ><a href="/?t=school" class="a1">机构</a></li>
				<li id="teacher"><a href="/?t=teacher" class="a4">教师</a></li>
				<li id="student"><a href="/?t=student" class="a5">学生</a></li>
        <li class="thwork" id="famous" style="border-right-width: 0px; border-bottom-width: 0px;"><a href="/?t=famous" class="a8">工作室</a></li>
				<li id="group"><a href="/?t=group" class="a6">群组</a></li>
        <li id="class"><a href="/?t=class" class="a3">班级</a></li>
        <li id="arts"><a href="/?t=arts" class="a9">新闻</a></li>
        <li id="actives"><a href="/?t=actives" class="a11">活动</a></li>
        <li><a href="/man" class="a12">管理</a></li>
			</ul>
		</div>
    <div class="clear"></div>
    