<div class="top_ad" style="background-image:url(/upds/school/logo/bnr_{id}.jpg);">
	<div class="top_logo" >
    	<div class="top_logo_pic">
   	    <img src="/upds/school/logo/{id}.jpg" onerror="this.src='/error/logo.jpg';" width="94" height="93">
         </div>
   	  <div class="top_txt">
        	<ul>
            	<li class="cn">{name}</li>
            	<li class="en">{mininame}</li>
            </ul>        
        </div>    
    </div>
</div>
<!--菜单开始-->
<div class="top_menu">
	<div class="menu_left">
      <div class="txt green"><a href="./?s={s}">首页</a></div>
      <div class="txt"><a href="./?t=class&s={s}">班级</a></div>
      <div class="txt"><a href="./?t=group&s={s}">群组</a></div>
      <div class="txt"><a href="./?t=famous&s={s}">工作室</a></div>
      
      <div class="txt"><a href="./?t=news&s={s}">校园新闻</a></div>
      <div class="txt"><a href="./?t=topics&s={s}">校园专题</a></div>         
      <div class="txt"><a href="/teacher?s={s}">教师空间</a></div>                
      <div class="txt noneborder"><a href="./man?s={s}" target=_blank>[管理]</a></div>
    </div>
	<div class="menu_right">
    	<div><a href="/subject?s={s}"  class="glyphicon glyphicon-grain">学科</a></div>          
   </div>
    
</div>