<div class="nav_in" style="margin-top:10px;">
	<ul class="main menu_in">
		<li><a href="/?t=index" target="">空间首页</a></li>
		<li><a href="" target="">父母学堂</a></li>
		<li><a href="" target="">名师博客</a></li>
		<li><a href="" target="">充电学习</a></li>
		<li><a href="" target="">活动中心</a></li>
		<li><a href="" target="">亲子资源</a></li>
		<li><a href="" target="">精品课程</a></li>
	</ul>
</div>
<div class="clear"></div>