<div class="nav_in" style="margin-top:10px;">
	<ul class="main menu_in">
		<li><a href="/?t=class" target="">班级主页</a></li>
		<li><a href="" target="">班级资讯</a></li>
		<li><a href="" target="">最新加入</a></li>
		<li><a href="" target="">推荐班级</a></li>
		<li><a href="" target="">发现班级</a></li>
		<li><a href="" target="">班级荣誉</a></li>
		<li><a href="" target="">推荐资源</a></li>
		<li><a href="" target="">今日学生</a></li>
		<li><a href="" target="">今日老师</a></li>
	</ul>
</div>
<div class="clear"></div>