<meta charset="gbk">   
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon" />
<link rel="stylesheet" href="/widget/bootstrap/css/bootstrap.min.css">  
<link rel="stylesheet" href="/widget/font-awesome/css/font-awesome.min.css">   
<script src="/ppf/js/jquery-1.min.js"></script>                    
<script src="/widget/bootstrap/js/bootstrap.min.js"></script>   
<script src="/ppf/js/jquery.base64.js" type="text/javascript"></script>
<script src="/ppf/js/cookies.min.js" type="text/javascript"></script> 
<script src="/ppf/js/fun.js" type="text/javascript"></script> 
<script src="/js/comm_login_bt.js" type="text/javascript"></script>
<script src="/js/local.js" type="text/javascript"></script>
<script src="/widget/layerv2/layer/layer.js" type="text/javascript"></script>
<link href="/html/blog/css/plat.css" rel="stylesheet" type="text/css">
<link type="image/x-icon" rel="shortcut icon" href="/imgs/favicon.ico">