<div class="nav_c">
	<ul class="main menu">
		<li class="menu01 fl">
			<dl>  
				<dt><i class="cir_cion men_cion1 fl"></i><a href="#" target="">网站首页</a></dt>
				<dd><a href="#" target="">同心圆介绍</a></dd>
				<dd><a href="#" target="">新闻速递</a></dd>
				<dd><a href="#" target="">&nbsp;亲子活动</a></dd>
				<dd><a href="#" target="">&nbsp;&nbsp;合作机构</a></dd>
			</dl>
		</li> 
		<li class="menu02 fl">
			<dl>
				<dt><i class="cir_cion men_cion2 fl"></i><a href="#" target="">家长学校</a></dt>
				<dd><a href="#" target="">习惯养成</a></dd>
				<dd><a href="#" target="">营养健康</a></dd>
				<dd><a href="#" target="">安全教育</a></dd>
				<dd><a href="#" target="">亲子关系</a></dd>
        <dd><a href="#" target="">心理健康</a></dd>
        <dd><a href="#" target="">潜能开发</a></dd>
			</dl>
		</li>
		<li class="menu03 fr">
			<dl> 
				<dt><i class="cir_cion men_cion3 fl"></i><a href="#" target="">父母课堂</a></dt>
				<dd><a href="/?t=school" target="">机构</a></dd>
				<dd><a href="/?t=blog" target="">空间</a></dd>
				<dd><a href="/?t=famous" target="">工作室</a></dd>
				<dd><a href="/?t=group" target="">群组</a></dd>
				<dd><a href="/?t=class" target="">班级</a></dd>
				<!--<dd><a href="#" target="">资源</a></dd>-->
        <dd><a href="/read" target="">悦读</a></dd>
				<dd><a href="#" target="">视频</a></dd>
				<dd><a href="#" target="">&nbsp;&nbsp;课程</a></dd>
				<dd><a href="/?t=actives" target="">&nbsp;活动</a></dd>
				<dd><a href="/subjecter" target="_blank">研修</a></dd>
			</dl>
		</li>
	</ul>
</div>
<div class="clear"></div>