<div class="nav_in" style="margin-top:10px;">
	<ul class="main menu_in">
		<li><a href="/?t=famous" target="">工作室主页</a></li>
		<li><a href="/?t=famous_search" target="">特色工作室</a></li>
		<li><a href="/?t=famous_search" target="">发现工作室</a></li>
		<li><a href="javascript:void(0);" target="">名师课堂</a></li>
		<li><a href="javascript:void(0);" target="">学科资源</a></li>
		<li><a href="/?t=actives" target="">最新活动</a></li>
		<li><a href="/?t=famous_list" target="">工作室动态</a></li>
	</ul>
</div>
<div class="clear"></div>