<div class="nav_in" style="margin-top:10px;">
	<ul class="main menu_in">
		<li><a href="/?t=group" target="">群组主页</a></li>
		<li><a href="/?t=group_search" target="">推荐群组</a></li>
		<li><a href="/?t=group_search" target="">发现群组</a></li>
		<li><a href="" target="">热门帖子</a></li>
		<li><a href="" target="">最新发布</a></li>
		<li><a href="" target="">热门群组</a></li>
		<li><a href="/?t=teacher_search" target="">活跃成员</a></li>
		<li><a href="" target="">资源共享</a></li>
	</ul>
</div>
<div class="clear"></div>