<div class="nav_in" style="margin-top:10px;">
		<ul class="main menu_in">                                                                                                                  
			  <li id="school_search"><a href="/?t=school_search" class="a1">机构</a></li>
				<li id="teacher_search"><a href="/?t=teacher_search" class="a4">教师</a></li>
				<li id="student_search"><a href="/?t=student_search" class="a5">学生</a></li>
        <li class="thwork" id="famous_search" style="border-right-width: 0px; border-bottom-width: 0px;"><a href="/?t=famous_search" class="a8">工作室</a></li>
				<li id="group_search"><a href="/?t=group_search" class="a6">群组</a></li>
        <li id="class_search"><a href="/?t=class_search" class="a3">班级</a></li>
        <li id="arts"><a href="/?t=arts" class="a9">新闻</a></li>
        <li id="actives"><a href="/?t=actives" class="a11">活动</a></li>
        <li><a href="/man" class="a12">管理</a></li>
		</ul>
</div>