 
<script src="/ppf/js/jquery-2.min.js"></script>                    
<script src="/widget/bootstrap/js/bootstrap.min.js"></script>   
<script src="/ppf/js/jquery.base64.js" type="text/javascript"></script>
<script src="/ppf/js/cookies.min.js" type="text/javascript"></script> 
<script src="/ppf/js/fun.js" type="text/javascript"></script> 
<script src="/js/comm_login_bt.js" type="text/javascript"></script>
<script src="/js/local.js" type="text/javascript"></script>
<script src="/widget/layerv2/layer/layer.js" type="text/javascript"></script>
<link href="/html/blog/css/blog.css" rel="stylesheet" type="text/css">