<!--icon-->
<div class="xcl_icon">
    <div class="xcl_icon_group">
    	<span  class="gopng_icon-1_outer gopng_icon-1" ></span>
        <a href="/?t=index">首页</a>
    </div>
    <div class="xcl_icon_group">
    	<span class="gopng_icon-2_outer gopng_icon-2"  /></span>
        <a href="/?t=school">机构</a>
    </div>
	<div class="xcl_icon_group">
    	<span class="gopng_icon-3_outer gopng_icon-3" /></span>
        <a href="/?t=blog">空间</a>
    </div>
    <div class="xcl_icon_group">
    	<span class="gopng_icon-4_outer gopng_icon-4" /></span>
        <a href="/?t=famous">工作室</a>
    </div>
    <div class="xcl_icon_group">
    	<span class="gopng_icon-5_outer gopng_icon-5" /></span>
        <a href="/?t=group">群组</a>
    </div>
     <div class="xcl_icon_group">
    	<span class="gopng_icon-6_outer gopng_icon-6" /></span>
        <a href="/?t=class">班级</a>
    </div>
     <div class="xcl_icon_group">
    	<span class="gopng_icon-7_outer gopng_icon-7" /></span>
        <a href="">资源</a>
    </div>
     <div class="xcl_icon_group">
    	<span class="gopng_icon-8_outer gopng_icon-8" /></span>
        <a href="">视频</a>
    </div>
     <div class="xcl_icon_group">
    	<span class="gopng_icon-9_outer gopng_icon-9" /></span>
        <a href="">课程</a>
    </div>
	<div class="xcl_icon_group no_margin">
    	<span class="gopng_icon-10_outer gopng_icon-10" /></span>
        <a href="/subjecter/" target="_blank">研修</a>
    </div>
    <div class="clear"></div>
</div>
<style type="text/css">
/*icon*/
.xcl_icon{width:1000px;margin-left:auto;margin-right:auto;margin-top:15px;}
.xcl_icon span{float:left;width:47px;height:47px;}
.xcl_icon_group a{font-size:14px;font-family:微软雅黑;color:#666666;float:left;display:block;margin-left:10px;margin-top:10px;}
.xcl_icon_group{float:left;margin-right:12px;}
.xcl_icon .no_margin{margin:0;}
</style>