<div class="nav_in" style="margin-top:10px;">
	<ul class="main menu_in">
		<li><a href="/?t=school" target="">机构主页</a></li>
		<li><a href="/?t=school_search" target="">热门机构</a></li>
		<li><a href="/?t=school_news" target="">教育新闻</a></li>
		<li><a href="/?t=school_search" target="">周边学校</a></li>
		<li><a href="/?t=class_search" target="">活跃班级</a></li>
		<li><a href="/?t=famous_search" target="">工作室推荐</a></li>
		<li><a href="/?t=group_search" target="">群组推荐</a></li>
		<li><a href="/?t=actives" target="">近期活动</a></li>
	</ul>
</div>
<div class="clear"></div>