<meta charset="gbk">  
<link href="/group/html/black/css/black-index.css" rel="stylesheet" type="text/css"> 
<link rel="stylesheet" href="/widget/bootstrap/css/bootstrap.min.css">  
<script src="/ppf/js/jquery-1.min.js"></script> 
<script src="/widget/bootstrap/js/bootstrap.min.js"></script>   
<script src="/ppf/js/jquery.base64.js" type="text/javascript"></script>
<script src="/ppf/js/cookies.min.js" type="text/javascript"></script> 
<script src="/ppf/js/fun.js" type="text/javascript"></script> 
<script src="/js/comm_login_bt.js" type="text/javascript"></script>
<script src="js/local.js" type="text/javascript"></script>
<!-- <link rel="stylesheet" type="text/css" href="js/main.css" media="all"> -->
<link href="/group/html/black/css/top.css" rel="stylesheet" type="text/css">